version: "3"
services:
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    restart: unless-stopped
volumes:
  mongodb_data_container:
